version: '3.9'
services:
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    volumes:
      - ./api/:/api
  db:
    image: mongo
    restart: always
    environment:
        - MONGO_INITDB_DATABASE=${GSM_DB_USER_AND_DB}
        - MONGO_INITDB_ROOT_USERNAME=${GSM_DB_USER_AND_DB}
        - MONGO_INITDB_ROOT_PASSWORD=${GSM_DB_PASSWORD}
    ports:
      - ${GSM_DB_PORT}:${GSM_DB_PORT}
    volumes:
      - mongodb:/data/db
      # - ./bot/db/:/docker-entrypoint-initdb.d/
  bot:
    build:
      context: ./
      dockerfile: ./bot/Dockerfile
    depends_on:
      - db
    environment:
      - GSM_TG_BOT_TOKEN=${GSM_TG_BOT_TOKEN:?err}
      - GSM_DB_HOSTNAME=${GSM_DB_HOSTNAME}
      - GSM_DB_USER_AND_DB=${GSM_DB_USER_AND_DB}
      - GSM_DB_PASSWORD=${GSM_DB_PASSWORD}
      - GSM_DB_PORT=${GSM_DB_PORT}
      - XBOX_CLIENT_SECRET_EXPIRY_DATE=${XBOX_CLIENT_SECRET_EXPIRY_DATE}
    volumes:
      - ./bot/:/bot

volumes:
  mongodb: