version: '3.9'
services:
  db:
    image: mongo
    restart: always
    environment:
        - MONGO_INITDB_DATABASE=${GSM_DB_USERNAME:?err}
        - MONGO_INITDB_ROOT_USERNAME=${GSM_DB_USERNAME:?err}
        - MONGO_INITDB_ROOT_PASSWORD=${GSM_DB_PASSWORD:?err}
    ports:
      - ${GSM_DB_PORT}:${GSM_DB_PORT}
    volumes:
      - mongodb:/data/db
      # - ./bot/db/:/docker-entrypoint-initdb.d/
  bot:
    build:
      context: .
    command: ["python3", "-u", "bot.py", "--localprod"]
    depends_on:
      - db
    environment:
      - GUB_BOT_TOKEN=${GUB_TESTING_BOT_TOKEN:?err}
      - GUB_PAYMENT_TOKEN=${GUB_TESTING_PAYMENT_TOKEN}
      - XBOX_CLIENT_SECRET_EXPIRY_DATE=${XBOX_CLIENT_SECRET_EXPIRY_DATE}
      - GSM_DB_URL_WITHOUT_USERNAME_AND_PASSWORD=${GSM_DB_URL_WITHOUT_USERNAME_AND_PASSWORD:?err}
      - GSM_DB_USERNAME=${GSM_DB_USERNAME:?err}
      - GSM_DB_PASSWORD=${GSM_DB_PASSWORD:?err}
    volumes:
      - ./bot/:/bot

volumes:
  mongodb: